#!/bin/bash

################################################################################
# Copyright (c) 2015, NEC Europe Ltd.
# All rights reserved.
# 
# Authors:
#          # 				  iotplatform@neclab.eu
#          # Flavio Cirillo - flavio.cirillo@neclab.eu
#          # Tobias Jacobs  
#          # Salvatore Longo
#          # Raihan Ul-Islam
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions 
# are met:
# 1. Redistributions of source code must retain the above copyright 
# notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above 
# copyright notice, this list of conditions and the following disclaimer 
# in the documentation and/or other materials provided with the 
# distribution.
# 3. All advertising materials mentioning features or use of this 
# software must display the following acknowledgment: This 
# product includes software developed by NEC Europe Ltd.
# 4. Neither the name of NEC nor the names of its contributors may 
# be used to endorse or promote products derived from this 
# software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY NEC ''AS IS'' AND ANY 
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN 
# NO EVENT SHALL NEC BE LIABLE FOR ANY DIRECT, INDIRECT, 
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED 
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH 
# DAMAGE.
##############################################################################/

#
# neciotplatform         Start/Stop the NEC IoT Platform
#
# chkconfig: 345 99 50
# description: NEC IoT Platform

### BEGIN INIT INFO
# Provides:          NEC IoT Broker
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NEC IoT Broker init script
# Description:       FIWARE IoT Broker GE reference implementation by NEC .
### END INIT INFO

PARAM=$1
IOTBDIR=/root/Aeron/
IOTBRUNNERDIR=IoTBroker-runner
STARTER=unix64_start-IoTBroker_as_Daemon.sh
STOPPER=unix64_stop-IoTBroker.sh

iotbroker_start()
{
    printf "%-50s" "Starting NEC IoT Platform..."
    
    cd $IOTBDIR/$IOTBRUNNERDIR/
    ./$STARTER > /dev/null 2>&1
   
   echo
}

iotbroker_stop()
{
	
	printf "%-50s" "Stopping NEC IoT Platform..."
	
    
    cd $IOTBDIR/$IOTBRUNNERDIR/
    ./$STOPPER > /dev/null 2>&1
    
    echo
}

iotbroker_status()
{
	status $STARTER
}


case ${PARAM} in

    'start')
        echo "Starting..."
        iotbroker_start
        ;;

    'stop')
        echo "Stopping..."
        iotbroker_stop
        ;;

    'restart')
        iotbroker_stop
        iotbroker_start
        ;;

    'status')
        iotbroker_status
        ;;

esac
